[package]
name = "viz-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
common = { path = "../common" }
futures = { workspace = true }
replay = { path = "../replay" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
