[package]
name = "feature-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
event-log = { path = "../event-log" }
serde = { workspace = true }
serde_json = { workspace = true }
