[package]
name = "searcher"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
event-log = { path = "../event-log" }
feature-engine = { path = "../feature-engine" }
serde = { workspace = true }
